apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.2.8
        ports:
        - containerPort: 27017
        resources: {}
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: mongodbuser
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: mongodbpwd
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  template: 
    metadata:       
      labels:
        app: api
    spec:            
      containers:
      - name: api
        image: kubedevio/api-produto:v1
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
          - name: MONGODB_URI
            value: mongodb://mongodbuser:mongodbpwd@mongo-service:27017/admin
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: LoadBalancer

